### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by pascalw** [kabisa/maji#1]
This is a meta issue that keeps track of the overall documentation state.

To do, document:
- [ ] TDD'ing with Cucumber and Mocha
- [ ] I18n
- [ ] Haml coffee templates
- [ ] Working with Cordova
- [ ] Bugsnag error tracking
- [ ] Per environment settings
- [ ] Make build system
- [ ] CSS autoprefixer
- [x] Iconfont builder (added in https://github.com/kabisaict/maji/pull/8)
- [x] Maji CLI
- [x] FAQ (added in https://github.com/kabisaict/maji/pull/8)
- [x] License (added in https://github.com/kabisaict/maji/pull/8)
- [ ] Semantic Versioning
- [x] How to upgrade to a newer version of Maji

**Comment by matthijsgroen** [comment]
How do you expect this documentation? Seperate MD files for each topic?

**Comment by pascalw** [comment]
Yes that would be fine.

**Comment by pascalw** [comment]
I'm going to close this issue as quite some documentation has been added over the last few months. If anything specific is missing feel free to open a new issue.
