### ISSUE TITLE
Extend events instead of overwriting them

### ISSUE THREAD

**Issue by RoelN** [kabisa/maji#105]
Example: we have some generic app-wide events we want to catch. Declaring events in views that extend the main application page will overwrite the original events. Solution:

```
constructor: ->
    @events = _.extend({}, ApplicationPage::events, @events)
    super
```

**Comment by matthijsgroen** [comment]
@RoelN This is not something that has to do with Maji. This is the nature of Backbone/Marionette. The problem lies in having events defined on a super class. This is project specific, and should be fixed in the specific project.

Closing for now.

**Comment by pascalw** [comment]
@matthijsgroen I agree however what we can do is make sure that out of the box this can't happen with the classes that Maji provides, mainly ApplicationPage. I'll have to look into this but that should be possible by not declaring the events in a regular events hash.
