### ISSUE TITLE
Use SVG icons instead of icon font

### ISSUE THREAD

**Issue by RoelN** [kabisa/maji#106]
Icon fonts are a hack, SVG icons FTW!

**Comment by pascalw** [comment]
@RoelN PR welcome :-)

**Comment by pascalw** [comment]
@RoelN would you use sprites with SVG too, to prevent having to load all icons one by one? Or would you inline in javascript or something like that?

**Comment by RoelN** [comment]
It should have a smart way to embed them in the page so you can style them through CSS. Spriting is not 100% necessary then, I think. A tool like [Grunticon](http://www.grunticon.com/) does what I want. I haven't looked at alternatives yet though.

**Comment by pascalw** [comment]
Ok interesting. Seems that Grunticon indeed inlines SVGs into CSS.

I don't think we'd have to bother with PNG fallbacks though, given that all the platforms we support support SVG out of the box.

**Comment by RoelN** [comment]
Yeah, PNG fallback can be ditched!

**Comment by RoelN** [comment]
I'd prefer a way where you can set the color through CSS, e.g.

```
.icon-cancel {
  fill: red;
}
.icon-ok {
  fill: green;
}
```

Some observations:
* Grunticon would generate two versions of the source SVG (plus uses an awkward way to determine colors in the file name)
* Re-use can only be done by the SVG `use` trick ([see here](https://css-tricks.com/svg-sprites-use-better-icon-fonts/)). Works in IE9+

**Comment by pascalw** [comment]
@RoelN what's the outcome of your research? Yay or nay?

**Comment by RoelN** [comment]
It depends.™

They both have their pros and cons. And some will matter in projects, some won't. So I'd prefer to choose your method from Maji Extra's, and not having one solution baked into Maji by default. Is that an option?

**Comment by pascalw** [comment]
That's an option but not sure if it's worth it. I'm fine keeping icon fonts built in and have projects use SVG when they see fit. In any case I don't think we should make any changes for this for 2.0.

**Comment by RoelN** [comment]
When we've worked a bit more with the SVG alternative it might help deciding. I still hope it'll be optional in the end, but can live with keeping it in for now :)

**Comment by RoelN** [comment]
So it's in Maji 3?! 

\o/

**Comment by ruisalgado** [comment]
yap! closing this since it's part of #152 already
