### ISSUE TITLE
Update Lato font, or use better default font

### ISSUE THREAD

**Issue by RoelN** [kabisa/maji#115]
Original version of Lato has a line-height issue where the line-height is too tall in Android 4.2 and 4.3 (possibly others, haven't tested). Grab Lato from Google (as opposed to the site of the original designer) and update ours to be sure.

Note: perhaps it's even beter to use system fonts for the "native feel". E.g. Roboto on Android, Helvetica Neue/San Fransisco on iOS.

**Comment by pascalw** [comment]
@RoelN I agree it makes sense to ship without a custom font by default:

* It's easy enough to include a custom font in your project if need be
* Makes the app feel more native
* Saves a bit on initial load time and binary size

Common approach [seems](https://css-tricks.com/os-specific-fonts-css/) [to be](https://medium.design/system-shock-6b1dc6d6596f#.lwtc5j2vi) to list several well known system fonts in a specific order.

I'll create a PR for this.

**Comment by pascalw** [comment]
Fixed by #116
