### ISSUE TITLE
Add link to kananda in new project template

### ISSUE THREAD

**Issue by matthijsgroen** [kabisa/maji#122]
This will help users just starting where they can find more complex examples to learn

**Comment by pascalw** [comment]
@eirvandelden what's the progress on updating the Kananda app to 2.0? I think we shouldn't add the link until that's completed.

**Comment by eirvandelden** [comment]
I'm agreeing with putting this on hold until Kandanda has been upgraded. 

Current status: I'm fighting a bit with my available time. I'm hoping to start the actual upgrade proces this week. Replacing the current layout with flex box later on…

**Comment by pascalw** [comment]
Closing this. Kandanda app is still on Maji 1x. Not sure if there's much value in upgrading it either.
