### ISSUE TITLE
Docs on how to run `2-0-stable`

### ISSUE THREAD

**Issue by ariejan** [kabisa/maji#136]
As someone new to Maji, I might want to skip installing 1.x and dive directly into 2.x. The [README in the 2-0-stable branch](https://github.com/kabisa/maji/blob/2-0-stable/README.md) is unclear on how to proceed (and does not even work, as `npm install maji` will give you a 1.x release at this time.

**Comment by pascalw** [comment]
`2-0-stable` is close to being released. I don't really want to put time into documenting how to use this branch when it's so close to be merged into master.

**Comment by ariejan** [comment]
👍
