### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by eirvandelden** [kabisa/maji#14]
**Environment**
Windows 8.1 with Cygwin

**What I did** 
`$ ./node_modules/.bin/maji new nl.kabisa.kandanda kandanda/`

**What I expected**
My new Maji App named kandanda

**What actually happened**

``` bash
events.js:85
    throw er; // Unhandled 

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn C:\Users\kabisa\Documents\node_modules\maji\script\create-project ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```

I believe this has to do with the bash script using commands that do not exist under Windows.
I've seen some other projects where they've "solved" this by adding a separate batch script

**Comment by pascalw** [comment]
Closing as at the moment we don't have a lot of demand to build Maji projects on Windows.
