### ISSUE TITLE
Is it APP_ENV or NODE_ENV?

### ISSUE THREAD

**Issue by matthijsgroen** [kabisa/maji#153]
In the `package.json` the `APP_ENV` var is prepared. In the Webpack config, both the `APP_ENV` and `NODE_ENV` vars are checked to determine if we are doing a production build

For termining the right set of settings, the `NODE_ENV` is the only one checked.

https://github.com/kabisa/maji/blob/f3c98f73e2e764260e4e802231a1eedb14530fe2/project_template/src/config/settings.js#L1

For me, this is confusing. should we check for `APP_ENV` in the process of including the right settings?

**Comment by pascalw** [comment]
This is a backwards compatiblity thing. Maji 2 used `APP_ENV`, but more and more libraries and tools perform optimizations if `NODE_ENV` is `production`. Preact does this, as well as Webpack. 

So bottom line: we need to set `NODE_ENV`. I have a slight preference for `APP_ENV` over `NODE_ENV` because it's a bit more fitting but then again NODE_ENV is more common. 

What do you think? I could live with just sticking to NODE_ENV.

**Comment by ruisalgado** [comment]
+1 on just using NODE_ENV

**Comment by matthijsgroen** [comment]
how would that play out for 'staging'? I want a 'production' type build, but with 'staging' settings :-)

**Comment by pascalw** [comment]
@matthijsgroen I've introduced an `APP_STAGE` variable for this in one of my apps. Building then becomes `APP_STAGE=staging bin/maji build --release android` or `NODE_ENV=production APP_STAGE=staging yarn build`. 

I would add this to the project template though. For many apps that's probably over complicated. 

You could even derive NODE_ENV from `APP_STAGE` of course to simply further. Something like `if [staging, production].include(APP_STAGE) NODE_ENV=production` etc

**Comment by matthijsgroen** [comment]
Ok so to summarize: 

- in the webpack config NODE_ENV will be used for build optimization
- in the package.json APP_STAGE will be used (for development/staging/test/production)
- in the settings `export default require(`./settings.${process.env.APP_STAGE}.json`); ` will be used.

optionally, in the wepack config, the NODE_ENV could be derived from the APP_STAGE.

correct?

**Comment by ruisalgado** [comment]
I guess Pascal meant he would **NOT** add it to the template. I agree.

I'd use `APP_STAGE`/`APP_ENV` exclusively for requiring the settings file, and I'd default it to the value of `NODE_ENV`. You could set it as needed in either package.json or outside in the environment. Everywhere else, `NODE_ENV` would be used.

**Comment by pascalw** [comment]
I'll check my app later when I have access to my computer again, but I think that's exactly what I did indeed.

**Comment by pascalw** [comment]
@ruisalgado I indeed meant **not** adding it to the template, I've updated my comment to reflect this.

**Comment by matthijsgroen** [comment]
The inclusion of settings is *IN* the project template right? So people have to adjust that manually for each project?

**Comment by ruisalgado** [comment]
the inclusion of settings is in the project template. What's being suggested is using only `NODE_ENV` for the project template - for simplicity and because it may suffice in many cases.

**Comment by matthijsgroen** [comment]
I will close this issue, since #157 is merged
