### ISSUE TITLE
[Maji3] Platform classes don't get added anymore

### ISSUE THREAD

**Issue by RoelN** [kabisa/maji#165]
The `platform-ios` etc. classed don't get added to `body`, so we can't make exceptions in the CSS anymore (e.g. adding extra room to the top of the page so account for the iOS bar)

**Comment by pascalw** [comment]
Hey @RoelN thanks for reporting this. Looks like the project template is missing an import statement for maji, e.g. `import "maji"`. I'll add this to the template. For your project you can simply add that import in `src/index.js`.

**Comment by RoelN** [comment]
Works like a charm! 👌 

I notice the `platform-web` class doesn't get added. Did we only to that in $CUSTOMER_PROJECT? It might be useful for other projects?

**Comment by pascalw** [comment]
I think we did that custom in that $CUSTOMER_PROJECT indeed ;-) But, it makes sense to add this to Maji proper. PR welcome ;-)
