### ISSUE TITLE
Rename folder for translations

### ISSUE THREAD

**Issue by ljpengelen** [kabisa/maji#175]
The translations (en.yml) are stored in a folder called "locales". I propose to rename that folder to something like "translations".

**Comment by pascalw** [comment]
The reason it's called `locales` is that's what it's called in Rails. The i18n library we're using is extracted from Rails.

Besides that, this directory strictly doesn't only contain translations either. It also contains stuff related to locales, like date formats. (See https://github.com/fnando/i18n-js#date-formatting for details).

**Comment by ljpengelen** [comment]
My definition of the word "locale" is probably too restricted.
