### ISSUE TITLE
Cordova complains if dist directory is removed

### ISSUE THREAD

**Issue by pascalw** [kabisa/maji#181]
I haven't investigated this but in some cases the `dist/` directory can get removed in which case Cordova contains that the current directory is not a Cordova project.

**Comment by pascalw** [comment]
I *think* this might happen either due to Webpack cleaning (and deleting?) the `dist/` directory and/or `dist/` is probably in `.gitignore` so after cloning a new project this might happen too.

**Comment by ruisalgado** [comment]
indeed we should clean the contents of the dir w/o removing it, and on project setup create the dir and the `cordova/www` symlink

**Comment by leonderijke** [comment]
Current workaround is to either either create the `dist/` directory via `mkdir dist` or running a Webpack build via `bin/maji build`.

**Comment by pascalw** [comment]
This was fixed by #195.
