### ISSUE TITLE
iOS Simulator run fails with latest XCode

### ISSUE THREAD

**Issue by leonderijke** [kabisa/maji#182]
When running `bin/maji run -e ios` with the latest XCode installed it fails to open the simulator. The Build succeeded, but the simulator couldn't be deployed to:

```
** BUILD SUCCEEDED **

No target specified for emulator. Deploying to undefined simulator
Device type "com.apple.CoreSimulator.SimDeviceType.undefined" could not be found.
```

In [this GitHub issue](https://github.com/phonegap/ios-sim/issues/218#issuecomment-330704710) I found a working solution: `bin/cordova platform rm ios && bin/cordova platform add ios@4.5.0`.

**Comment by franbueno** [comment]
Same error :(
