### ISSUE TITLE
Page Transition doesn't account for rendering the same component

### ISSUE THREAD

**Issue by leonderijke** [kabisa/maji#183]
Given this route: `<TestPage path="/test/:foo?" />`, when transitioning from `/test/` to `/test/bar` (and vice versa) a transition is prevented. This causes `TestPage` to render with an empty `foo` param.

The reason for this is that the state of the `PageContainer` will only be updated when rendering different components (the check is currently `nextPage.nodeName !== previousPage.nodeName`). The state will not be updated when rendering the same component with different props.

**Comment by ruisalgado** [comment]
@leonderijke can u give #184 a go? should solve this

**Comment by leonderijke** [comment]
Yes, #184 fixes this problem!

**Comment by leonderijke** [comment]
Since #184 is merged, I'm closing this issue.
