### ISSUE TITLE
Run e2e tests with headless Chrome

### ISSUE THREAD

**Issue by leonderijke** [kabisa/maji#199]
For the unit tests we're currently using headless Chrome, but for the e2e tests apparently not yet. It would be useful if the e2e tests could run using headless Chrome as well, as this removes the need to use `xvfb-run` in the `Jenkinsfile`s.

**Comment by ruisalgado** [comment]
@leonderijke I'm trying to address this in #200

**Comment by pascalw** [comment]
Closed by #200.
