### ISSUE TITLE
Add Windows Phone 8 build support

### ISSUE THREAD

**Issue by pascalw** [kabisa/maji#2]
Previous X-Mobile projects used setup with Windows 8.1 running Virtualbox. See how to extract this generically, or document how to set it up for projects.

**Comment by stefanvr** [comment]
We know have an VM and way of working with this machine locally or within the CI system.

This is however currently only available for Kabisa. We could publish the step to set it up, but as licences are involved it will be hard to do anything other than that.

**Comment by pascalw** [comment]
Closing as at the moment we don't have a lot of demand to for Windows Phone support.

**Comment by JoostSaanen** [comment]
I think contac-Lib needs to work on Windows 8. Isn't that build with Maji as well?
