### ISSUE TITLE
Not able to post form in production build android app

### ISSUE THREAD

**Issue by guidotheelen** [kabisa/maji#208]
The new version of Cordova needs a new plugin to allow navigation to urls. 

The fix is to include the cordova-plugin-whitelist plugin, and allow navigation to your desired page.

Include this code in cordova's config.xml to allow all navigation:
```xml
<plugin name=“cordova-plugin-whitelist” spec=“^1.3.3” />
<allow-navigation href="*" />
```

**Comment by guidotheelen** [comment]
Fixed by adding the following code.

<plugin name="cordova-plugin-whitelist" spec="~1.3.0" />
    

<allow-navigation href="*" />

**Comment by leonderijke** [comment]
(edited to add syntax highlighting to code blocks)
