### ISSUE TITLE
Non-headless e2e tests fail with recent chromedriver

### ISSUE THREAD

**Issue by ruisalgado** [kabisa/maji#225]
`stacktrace: 'org.openqa.selenium.WebDriverException: unknown error: cannot parse capability: chromeOptions\nfrom unknown error: cannot parse args\nfrom unknown error: must be a list\n`

This happens because in the `nonHeadless` nightwatch test env, we [set chromeOptions args to null](https://github.com/kabisa/maji/blob/master/project_template/config/nightwatch.js#L36).

Setting the args to `[]` doesn't work unfortunately, as there's a bug in nightwatch that will cause the default settings to be used, thus reintroducing `--headless`.

**Comment by ruisalgado** [comment]
Setting *any* valid arg will have nightwatch overwrite the default settings as expected. So while the `[]` bug persists, I'd suggest just setting some (seemingly innocuous) args from the [available list](https://peter.sh/experiments/chromium-command-line-switches/). Say... `--default` looks like a good candidate.

**Comment by pascalw** [comment]
Is there a Nightwatch issue for this we can track?

**Comment by leonderijke** [comment]
I'm writing one now. Will update with a link when I'm done.
