### ISSUE TITLE
Alias more Maji commands

### ISSUE THREAD

**Issue by eirvandelden** [kabisa/maji#24]
Currently it's not clear when to use a "Maji" command and when something else. During development these are the most important ones:

```
make watch
bin/karma start
bundle exec rspec
bin/ci
```

Perhaps it's better to alias them all as maji commands, for example:

```
maji watch
maji karma start
maji rspec
maji ci
```

**Comment by pascalw** [comment]
Going to proceed as follows:

* New projects will contain npm run scripts for common tasks (build, start, test, watch, build:app)
* `bin/maji` will delegate to these run scripts

**Comment by harm** [comment]
Nieuwsbrief Kabisa

Geen afbeeldingen?  Webversie http://newsletter.kabisa.nl/t/r-e-yuydviy-krfjiaur-e/

Nieuwsbrief Kabisa

Beste lezer,

Er is weer veel gebeurd bij Kabisa de afgelopen maanden. Mocht je ons  nieuws [https://kabisa.nl/nieuws] hebben gemist, dan vind je in deze nieuwsbrief een samenvatting.

We kijken terug op een aantal interessante workshops en trainingen die zijn gehouden door Kabisa. Ook zijn er weer enkele projecten succesvol afgerond.

Kabisa was het afgelopen kwartaal een aantal keer in het nieuws vanwege het winnen van de "Beste werkgever Award 2017". Lees hierover meer in deze nieuwsbrief.

Mocht je nog vragen hebben over bepaalde onderwerpen, neem dan gerust  contact met ons [https://kabisa.nl/contact] op.

Kabisa ontwikkelt webapplicatie voor Philips HueLabs

Philips Hue [https://www.googleadservices.com/pagead/aclk?sa=L&ai=DChcSEwin3MLLj_zTAhWBFdMKHTNGClgYABAKGgJ3Yg&ohost=www.google.nl&cid=CAASE-RozFdtmonRQ0PC8R1PTASvAE8&sig=AOD64_2PuhY5ofTfWrHsc6vktY1dmQcmnw&q=&ved=0ahUKEwjOvr7Lj_zTAhUJYVAKHcSOC-cQ0QwIPw&adurl=] is een persoonlijk draadloos verlichtingssysteem: een product gebaseerd op eigen behoeften en levensstijl. In 2016 is Kabisa samen met Philips Lighting begonnen aan het ontwikkelen van een vernieuwde versie van de HueLabs webapplicatie. Onlangs is deze nieuwe Huelabs webapplicatie gelanceerd!

Lees meer over dit project [https://www.kabisa.nl/portfolio/philips-huelabs/]                   Nieuwe mobiele app Cocktail Week Amsterdam

Begin maart heeft de  Amsterdam Cocktail Week [http://www.amsterdamcocktailweek.nl/] plaatsgevonden. Kabisa heeft in het kader van dit event een mobiele app ontwikkeld.

Lees meer over dit project [https://www.kabisa.nl/nieuws/kabisa-ontwikkelt-app-voor-amsterdam-cocktail-week/]                   Kabisa bij BNR

Dinsdag 9 mei werd Harm de Laat, medeoprichter van Kabisa, geïnterviewd door Rens de Jong van BNR nieuwsradio. Onderwerp van het programma: employer branding.

Beluister de radiouitzending [https://www.kabisa.nl/nieuws/hoe-word-je-een-aantrekkelijke-werkgever/]            Overige highlights

Codecation: beter leren programmeren tijdens een vakantie [https://www.kabisa.nl/nieuws/codecation-beter-leren-programmeren-tijdens-een-vakantie/]

Kabisa organiseert succesvolle Elixir Bootcamp in Amsterdam [https://www.kabisa.nl/nieuws/kabisa-organiseert-succesvolle-elixir-bootcamp-in-amsterdam/]

Kabisa verzorgt technisch colloquium fontys venlo [https://www.kabisa.nl/nieuws/kabisa-verzorgt-technisch-colloquium-fontys-venlo/] Elixir talks night Zuid-Nederland [https://www.kabisa.nl/nieuws/elixir-talks-night-zuid-nederland/] Beroepenvoorlichting bij Bisschoppelijk College Weert [https://www.kabisa.nl/nieuws/beroepenvoorlichting-bij-bisschoppelijk-college-weert/] Kabisa verzorgt Ruby en Elixir workshop in Duitsland [https://www.kabisa.nl/nieuws/kabisa-verzorgt-ruby-en-elixir-workshop-in-duitsland/] Waarom wij onze collega's kudo's geven? [https://www.kabisa.nl/nieuws/waarom-wij-onze-collega-s-kudos-geven/] Kabisa in de krant [https://www.kabisa.nl/nieuws/kabisa-in-de-krant/]                  Vacatures

Wij zijn nog steeds op zoek naar collega's. Er zijn  verschillende functies vacant [https://kabisa.nl/werken-bij]. Zo zoeken wij nog een Modern Java Web Developer. Is deze functie iets voor jou?  Bekijk dan de vacature en reageer! [https://www.kabisa.nl/vacatures/modern-java-web-developer/]

Lees ook onze laatste blogposts Leestip: Mobiele apps voor bedrijven [https://blog.kabisa.nl/mobiele-apps-voor-bedrijven/] Leestip: Progressive web apps [https://blog.kabisa.nl/progressive-web-apps/] Leestip: 5 voordelen van hybride app development [https://blog.kabisa.nl/moet-je-als-startup-beginnen-met-een-schaalbare-infrastructuur/] Moet je als startup beginnen met een schaalbare infrastructuur? [https://blog.kabisa.nl/moet-je-als-startup-beginnen-met-een-schaalbare-infrastructuur/] Waarom zou je voor microservices kiezen [https://blog.kabisa.nl/waarom-zou-je-voor-microservices-kiezen/] Onderscheid met 3d je website, webapplicatie of mobiele app [https://blog.kabisa.nl/onderscheid-met-3d-je-website-webapplicatie-of-mobiele-app/] weet je wat je als bedrijf allemaal met WhatsApp kunt doen [https://blog.kabisa.nl/weet-je-wat-je-als-bedrijf-allemaal-met-whatsapp-kunt-doen/] Mobiele app ontwikkeling voor evenementen en festivals [https://blog.kabisa.nl/mobiele-app-ontwikkeling-voor-evenementen-en-festivals/] Geen (zichzelf) respecterende DevOps-engineer kan zonder [https://blog.kabisa.nl/geen-zichzelf-respecterende-devops-engineer-kan-zonder/] Een app submitten naar de app store zonder wachttijd [https://blog.kabisa.nl/een-app-submitten-naar-de-app-store-zonder-wachttijd/] Automatisch testen van een mobiele app op wel 100 apparaten tegelijk [https://blog.kabisa.nl/automatisch-testen-van-een-mobiele-app-op-wel-100-apparaten-tegelijk/]                       Wat kan Kabisa voor jou betekenen?

Kabisa heeft voor het bedrijf Wuunder een mobiele app ontwikkeld.

De Wuunder app maakt het mogelijk om op een innovatieve manier pakketten, documenten of pallets te verzenden. Wat uniek is aan de app is dat zender en ontvanger in contact kunnen blijven via chatberichten.

Bekijk de portfolio [https://www.kabisa.nl/portfolio/wuunder/]                      U ontvangt deze nieuwsbrief omdat u een belangrijke relatie van ons bedrijf bent.Mocht u desondanks geen behoefte hebben aan deze nieuwsbrief, dan kunt u onderstaande link gebruiken om uit te schrijven.

Vind ik leuk http://newsletter.kabisa.nl/t/r-fb-yuydviy-krfjiaur-s/

Tweet http://newsletter.kabisa.nl/t/r-tw-yuydviy-krfjiaur-g/

Deel [http://newsletter.kabisa.nl/t/r-li-yuydviy-krfjiaur-tj/]

Doorsturen http://kabisa.forwardtomyfriend.com/r-krfjiaur-12CB2BD3-yuydviy-l-w

Voorkeuren aanpassen http://kabisa.updatemyprofile.com/r-yuydviy-12CB2BD3-krfjiaur-yd  |   Uitschrijven http://newsletter.kabisa.nl/t/r-u-yuydviy-krfjiaur-yh/

**Comment by harm** [comment]
Nieuwsbrief Kabisa

Geen afbeeldingen?  Webversie http://newsletter.kabisa.nl/t/r-e-yuhhchl-krfjiaur-h/

Kabisa opent derde kantoor

Kabisa opent haar derde kantoor in Eindhoven. Het kantoor is het antwoord op een toenemende vraag naar software dienstverlening en staat in de lijn van de strategie van Kabisa om verder te groeien in Nederland.

Om haar ambities waar te maken en nog dichter bij de klant te staan en aantrekkelijke werkgever te zijn voor medewerkers uit de regio Noord-Brabant opent Kabisa haar 3e kantoor.

Het nieuwe kantoor is gevestigd aan de  Mathildelaan 1 te Eindhoven [https://goo.gl/RDcqOK]. Door de moderne en natuurlijke vormgeving, straalt het kantoor openheid en frisheid uit. De inrichting van het interieur nodigt medewerkers uit om elkaar op te zoeken.

Kom gerust eens kijken!

Benieuwd naar ons kantoor? Bekijk onze site [https://www.kabisa.nl/nieuws/kabisa-opent-derde-kantoor/]                   Wil jij werken bij de beste werkgever van Nederland?

Wij zijn nog steeds op zoek naar collega's. Naast ons nieuw kantoor in Eindhoven, zijn er ook mogelijkheden op onze kantoren in Weert en Amsterdam. De volgende functies zijn vacant:

Ruby on Rails Developer (Lead) [https://www.kabisa.nl/vacatures/ruby-developer] Modern Java Backend Developer [https://www.kabisa.nl/vacatures/modern-java-backend-developer] Modern Java Web Developer [https://www.kabisa.nl/vacatures/modern-java-web-developer] Elixir / Phoenix developer [https://www.kabisa.nl/vacatures/elixir-phoenix-developer] Frontend Developer [https://www.kabisa.nl/vacatures/frontend-developer] DevOps Engineer [https://www.kabisa.nl/vacatures/devops-engineer]

U ontvangt deze nieuwsbrief omdat u een belangrijke relatie van ons bedrijf bent. Mocht u desondanks geen behoefte hebben aan deze nieuwsbrief, dan kunt u onderstaande link gebruiken om uit te schrijven.

Vind ik leuk http://newsletter.kabisa.nl/t/r-fb-yuhhchl-krfjiaur-k/

Tweet http://newsletter.kabisa.nl/t/r-tw-yuhhchl-krfjiaur-u/

Deel [http://newsletter.kabisa.nl/t/r-li-yuhhchl-krfjiaur-v/]

Doorsturen http://kabisa.forwardtomyfriend.com/r-krfjiaur-12CB2BD3-yuhhchl-l-o

Voorkeuren aanpassen http://kabisa.updatemyprofile.com/r-yuhhchl-12CB2BD3-krfjiaur-b  |   Uitschrijven http://newsletter.kabisa.nl/t/r-u-yuhhchl-krfjiaur-n/
