### ISSUE TITLE
Documentation is spread over multiple sources

### ISSUE THREAD

**Issue by ljpengelen** [kabisa/maji#258]
It might be a good idea to delete the wiki and stick with documentation as Markdown in the repo itself as the only source of documentation.

**Comment by ljpengelen** [comment]
I'm happy to make a PR to migrate whatever is still relevant from the wiki to the other documentation, but it seems to me that there's only outdated information left in the wiki.

**Comment by pascalw** [comment]
I agree. I removed the wiki feature of this repo.
