### ISSUE TITLE
Preact-router does not have to be a peer dependency anymore

### ISSUE THREAD

**Issue by ljpengelen** [kabisa/maji#259]
Preact-router is listed as a peer dependency of Maji in `package.json` and as an external in the Rollup configuration. I think that's no longer needed. You can use Maji without preact-router if you want, so it's not necessary to trigger a warning when it's not installed.

**Comment by pascalw** [comment]
You're right. https://github.com/kabisa/maji/blob/e43d33367b1fe50afaad31649edf7bbd2eeffa97/src/pageTransitionSupport.js is a HOC now, so there's no compile dependency on `preact-router`.
