### ISSUE TITLE
Is 'supported-browsers' code actually needed?

### ISSUE THREAD

**Issue by bazzel** [kabisa/maji#262]
When generating a new Maji project, some setup is done for which browsers are supported using [https://github.com/browserslist/browserslist](browserslist). But according to [its documentation](https://github.com/browserslist/browserslist#queries) the `browserslist` file (which will end up in the root of the generated Maji project) is found and interpreted automagically.

If so, this means that we don't need:
* `project_template/config/supported_browsers.js` 
* `targets` key (and corresponding `require`) in `project_template/config/babel.js`
* `browsers` key (and corresponding `require`) in `project_template/.stylelintrc.js`

Although I can create a PR, I'm currently not sure how to verify if my assumptions are correct. Running `npx browserslist` after removing it from an existing project shows the same list of browsers.

**Comment by pascalw** [comment]
Hi @bazzel I think your observations are correct. This stems from a time were the browserslist file was not yet picked up automatically by Babel.

I think the best way to verify this is to:
* Make the changes you proposed
* Run `npx autoprefixer --info` in the project and verify the output is still the same. (See https://github.com/postcss/autoprefixer#debug)
* Enable `debug` in `@babel/preset-env` and verify the output is still the same. (See https://babeljs.io/docs/en/babel-preset-env#debug)
