### ISSUE TITLE
Namespace the Maji-specific classes

### ISSUE THREAD

**Issue by RoelN** [kabisa/maji#41]
Some of the classes that Maji sticks on HTML elements sound kinda generic, like `page`, `animated` or `slide`. Would it be okay to prepend all of these with `maji-` to avoid clashes with the project's CSS?

**Comment by pascalw** [comment]
Sure, sounds good!

Op maandag 18 mei 2015 heeft Roel N <notifications@github.com> het volgende
geschreven:

> Some of the classes that Maji sticks on HTML elements sound kinda generic,
> like page, animated or slide. Would it be okay to prepend all of these
> with maji- to avoid clashes with the project's CSS?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kabisaict/maji/issues/41>.
>


-- 

Met vriendelijke groet,

Pascal Widdershoven
Kabisa

Marconilaan 8, 6003 DD, Weert
Kleine Gartmanplantsoen 10, 1017 RR, Amsterdam

email: pascal.widdershoven@kabisa.nl
web: http://www.kabisa.nl
mobile: +31 (0) 6 814 77 020
tel: +31 (0) 495 430 798
support tel: +31 (0) 495 430 593
support web: http://support.kabisa.nl
CoC: 14090089

**Comment by pascalw** [comment]
Delaying this until a next release

**Comment by RoelN** [comment]
Fixed in https://github.com/kabisa/maji/pull/154 for Maji 3, closing this issue.
