### ISSUE TITLE
Upgrade Marionette to 2.X

### ISSUE THREAD

**Issue by pascalw** [kabisa/maji#5]
Maji still uses Marionette 1.8. Upgrade to Marionette 2.1.
This mostly means renaming some methods.

**Comment by bazzel** [comment]
I updated a non-maji project from Marionette 1.8.x to 2.4.4 using https://github.com/marionettejs/Marionette.Upgrade and it actually went pretty smoothly.

**Comment by pascalw** [comment]
Taken care of by #93
