### ISSUE TITLE
bin/setup isn't called on a clean install of maji, when generating a new maji app

### ISSUE THREAD

**Issue by eirvandelden** [kabisa/maji#75]
Tried installing maji from npm on Robin's machine. After generating a new maji app, we couldn't build it, as we were missing some dependencies. Running bin/setup after generating the app allowed us to build again. It really was installing new node packages.

**Comment by pascalw** [comment]
Hm `bin/setup` should indeed be called as part of `maji new`. I just tried this myself and for me it is working as expected, so I guess there must be some specific scenario in which this happens. Can you provide some more information on how exactly this occurred?

Was `bin/setup` not called at all, or was it called but did it fail?

**Comment by eirvandelden** [comment]
Doh, that's it. It did fail at first, the Xcode command line tools were missing.
