### ISSUE TITLE
Maji seems not to be compatible w/ Node 5/npm 3

### ISSUE THREAD

**Issue by bazzel** [kabisa/maji#82]
After upgrading to Mac OS X 10.11 (El Capitan) and upgrading Node to v5.0.0 (and with it npm 3.3.9) maji prints out several errors.
Although you should expect maji to be able to handle an upgrade like this (I guess), I was able work around this by installing a version manager for Node which allows me to use different versions of Node and npm on one machine.

I prefer a more robust version of maji instead of using a version manager as a solution, but for now the following instructions could be useful:

```bash
$ node -v
v5.0.0
$ npm -v
3.3.9
```

* Install `n` as version manager:

  ```bash
  $ npm install -g n
  ```

* Install Node 4.2.2:

  ```bash
  $ n 4.2.2
  $ node -v
  v4.2.2
```

* Remove the `node_modules` folder from your app directory and run `node install`:

  ```bash
    $ rm -rf node_modules
    $ node install
  ```

* You will probably see an error addressing `node-sass`, which I cannot explain, but re-installing these, it will work:

  ```bash
    $ npm install node-sass
  ```

**Comment by bazzel** [comment]
Instead of `n` you might prefer another version manager, such as [`nvm`](https://github.com/creationix/nvm)

**Comment by pascalw** [comment]
@lucianleustean I think #93 takes care of this right?

**Comment by pascalw** [comment]
Current master is compatible with Node >=5 and npm 3.
