### ISSUE TITLE
Disable animations for incapable devices

### ISSUE THREAD

**Issue by RoelN** [kabisa/maji#95]
Do not provide a JavaScript fallback for CSS3 animations:
- These are probably older devices, better off without fancy CPU-powered animations
- It's hard to keep animationEnd in sync with the JavaScript timeout

Optinally make this turn on-and-offable in the settings.

**Comment by pascalw** [comment]
@RoelN can you explain your thoughts behind this? I'm not sure if devices not capable of running simple animations are something we should target? If specific applications want to support such devices that's fine, but I don't think we should go to lengths to support this in Maji proper.

**Comment by RoelN** [comment]
@pascalw My thoughts exactly :) If we stick to CSS3 animations, capable devices will get animations, and older devices won't. My issue is that Maji animates with jQuery when CSS animations aren't supported, if I'm correct. If so, we shouldn't do that.

**Comment by pascalw** [comment]
Got it. There's no JS animation fallback so I guess we're good :)

**Comment by RoelN** [comment]
I think @matthijsgroen still has a good idea to listen to transitionend instead of doing setTimeoutty stuff. New issue?

**Comment by pascalw** [comment]
Yes please!
